exports.weatherConditions = {
  1000: {
    code: 1000,
    day: 'Sunny',
    night: 'Clear',
    icon: 113,
    color: '#ffa922',
  },
  1003: {
    code: 1003,
    day: 'Partly cloudy',
    night: 'Partly cloudy',
    icon: 116,
    color: '#04bee3',
  },
  1006: {
    code: 1006,
    day: 'Cloudy',
    night: 'Cloudy',
    icon: 119,
    color: '#1cb48b',
  },
  1009: {
    code: 1009,
    day: 'Overcast',
    night: 'Overcast',
    icon: 122,
    color: '#86a4c8',
  },
  1030: {
    code: 1030,
    day: 'Mist',
    night: 'Mist',
    icon: 143,
    color: '#86a4c8',
  },
  1063: {
    code: 1063,
    day: 'Patchy rain possible',
    night: 'Patchy rain possible',
    icon: 176,
    color: '#00457c',
  },
  1066: {
    code: 1066,
    day: 'Patchy snow possible',
    night: 'Patchy snow possible',
    icon: 179,
    color: '#7ec5e3',
  },
  1069: {
    code: 1069,
    day: 'Patchy sleet possible',
    night: 'Patchy sleet possible',
    icon: 182,
    color: '#86a4c8',
  },
  1072: {
    code: 1072,
    day: 'Patchy freezing drizzle possible',
    night: 'Patchy freezing drizzle possible',
    icon: 185,
    color: '#00457c',
  },
  1087: {
    code: 1087,
    day: 'Thundery outbreaks possible',
    night: 'Thundery outbreaks possible',
    icon: 200,
    color: '#776e9d',
  },
  1114: {
    code: 1114,
    day: 'Blowing snow',
    night: 'Blowing snow',
    icon: 227,
    color: '#7ec5e3',
  },
  1117: {
    code: 1117,
    day: 'Blizzard',
    night: 'Blizzard',
    icon: 230,
    color: '#776e9d',
  },
  1135: {
    code: 1135,
    day: 'Fog',
    night: 'Fog',
    icon: 248,
    color: '#86a4c8',
  },
  1147: {
    code: 1147,
    day: 'Freezing fog',
    night: 'Freezing fog',
    icon: 260,
    color: '#86a4c8',
  },
  1150: {
    code: 1150,
    day: 'Patchy light drizzle',
    night: 'Patchy light drizzle',
    icon: 263,
    color: '#00457c',
  },
  1153: {
    code: 1153,
    day: 'Light drizzle',
    night: 'Light drizzle',
    icon: 266,
    color: '#00457c',
  },
  1168: {
    code: 1168,
    day: 'Freezing drizzle',
    night: 'Freezing drizzle',
    icon: 281,
    color: '#00457c',
  },
  1171: {
    code: 1171,
    day: 'Heavy freezing drizzle',
    night: 'Heavy freezing drizzle',
    icon: 284,
    color: '#00457c',
  },
  1180: {
    code: 1180,
    day: 'Patchy light rain',
    night: 'Patchy light rain',
    icon: 293,
    color: '#00457c',
  },
  1183: {
    code: 1183,
    day: 'Light rain',
    night: 'Light rain',
    icon: 296,
    color: '#00457c',
  },
  1186: {
    code: 1186,
    day: 'Moderate rain at times',
    night: 'Moderate rain at times',
    icon: 299,
    color: '#00457c',
  },
  1189: {
    code: 1189,
    day: 'Moderate rain',
    night: 'Moderate rain',
    icon: 302,
    color: '#00457c',
  },
  1192: {
    code: 1192,
    day: 'Heavy rain at times',
    night: 'Heavy rain at times',
    icon: 305,
    color: '#00457c',
  },
  1195: {
    code: 1195,
    day: 'Heavy rain',
    night: 'Heavy rain',
    icon: 308,
    color: '#00457c',
  },
  1198: {
    code: 1198,
    day: 'Light freezing rain',
    night: 'Light freezing rain',
    icon: 311,
    color: '#00457c',
  },
  1201: {
    code: 1201,
    day: 'Moderate or heavy freezing rain',
    night: 'Moderate or heavy freezing rain',
    icon: 314,
    color: '#00457c',
  },
  1204: {
    code: 1204,
    day: 'Light sleet',
    night: 'Light sleet',
    icon: 317,
    color: '#7ec5e3',
  },
  1207: {
    code: 1207,
    day: 'Moderate or heavy sleet',
    night: 'Moderate or heavy sleet',
    icon: 320,
    color: '#7ec5e3',
  },
  1210: {
    code: 1210,
    day: 'Patchy light snow',
    night: 'Patchy light snow',
    icon: 323,
    color: '#7ec5e3',
  },
  1216: {
    code: 1216,
    day: 'Patchy moderate snow',
    night: 'Patchy moderate snow',
    icon: 329,
    color: '#7ec5e3',
  },
  1219: {
    code: 1219,
    day: 'Moderate snow',
    night: 'Moderate snow',
    icon: 332,
    color: '#7ec5e3',
  },
  1222: {
    code: 1222,
    day: 'Patchy heavy snow',
    night: 'Patchy heavy snow',
    icon: 335,
    color: '#7ec5e3',
  },
  1225: {
    code: 1225,
    day: 'Heavy snow',
    night: 'Heavy snow',
    icon: 338,
    color: '#7ec5e3',
  },
  1237: {
    code: 1237,
    day: 'Ice pellets',
    night: 'Ice pellets',
    icon: 350,
    color: '#7ec5e3',
  },
  1240: {
    code: 1240,
    day: 'Light rain shower',
    night: 'Light rain shower',
    icon: 353,
    color: '#00457c',
  },
  1243: {
    code: 1243,
    day: 'Moderate or heavy rain shower',
    night: 'Moderate or heavy rain shower',
    icon: 356,
    color: '#00457c',
  },
  1246: {
    code: 1246,
    day: 'Torrential rain shower',
    night: 'Torrential rain shower',
    icon: 359,
    color: '#00457c',
  },
  1249: {
    code: 1249,
    day: 'Light sleet showers',
    night: 'Light sleet showers',
    icon: 362,
    color: '#00457c',
  },
  1252: {
    code: 1252,
    day: 'Moderate or heavy sleet showers',
    night: 'Moderate or heavy sleet showers',
    icon: 365,
    color: '#00457c',
  },
  1255: {
    code: 1255,
    day: 'Light snow showers',
    night: 'Light snow showers',
    icon: 368,
    color: '#7ec5e3',
  },
  1258: {
    code: 1258,
    day: 'Moderate or heavy snow showers',
    night: 'Moderate or heavy snow showers',
    icon: 371,
    color: '#7ec5e3',
  },
  1261: {
    code: 1261,
    day: 'Light showers of ice pellets',
    night: 'Light showers of ice pellets',
    icon: 374,
    color: '#7ec5e3',
  },
  1264: {
    code: 1264,
    day: 'Moderate or heavy showers of ice pellets',
    night: 'Moderate or heavy showers of ice pellets',
    icon: 377,
    color: '#7ec5e3',
  },
  1273: {
    code: 1273,
    day: 'Patchy light rain with thunder',
    night: 'Patchy light rain with thunder',
    icon: 386,
    color: '#776e9d',
  },
  1276: {
    code: 1276,
    day: 'Moderate or heavy rain with thunder',
    night: 'Moderate or heavy rain with thunder',
    icon: 389,
    color: '#776e9d',
  },
  1279: {
    code: 1279,
    day: 'Patchy light snow with thunder',
    night: 'Patchy light snow with thunder',
    icon: 392,
    color: '#776e9d',
  },
  1282: {
    code: 1282,
    day: 'Moderate or heavy snow with thunder',
    night: 'Moderate or heavy snow with thunder',
    icon: 395,
    color: '#7ec5e3',
  },
};

// exports.weatherConditions = {
//   {
//   code: 1000,
//     day: 'Sunny',
//       night: 'Clear',
//         icon: 113,
//           color: '#00cdf5',
//   },
// {
//   code: 1003,
//     day: 'Partly cloudy',
//       night: 'Partly cloudy',
//         icon: 116,
//   },
// {
//   code: 1006,
//     day: 'Cloudy',
//       night: 'Cloudy',
//         icon: 119,
//   },
// {
//   code: 1009,
//     day: 'Overcast',
//       night: 'Overcast',
//         icon: 122,
//   },
// {
//   code: 1030,
//     day: 'Mist',
//       night: 'Mist',
//         icon: 143,
//   },
// {
//   code: 1063,
//     day: 'Patchy rain possible',
//       night: 'Patchy rain possible',
//         icon: 176,
//   },
// {
//   code: 1066,
//     day: 'Patchy snow possible',
//       night: 'Patchy snow possible',
//         icon: 179,
//   },
// {
//   code: 1069,
//     day: 'Patchy sleet possible',
//       night: 'Patchy sleet possible',
//         icon: 182,
//   },
// {
//   code: 1072,
//     day: 'Patchy freezing drizzle possible',
//       night: 'Patchy freezing drizzle possible',
//         icon: 185,
//   },
// {
//   code: 1087,
//     day: 'Thundery outbreaks possible',
//       night: 'Thundery outbreaks possible',
//         icon: 200,
//   },
// {
//   code: 1114,
//     day: 'Blowing snow',
//       night: 'Blowing snow',
//         icon: 227,
//   },
// {
//   code: 1117,
//     day: 'Blizzard',
//       night: 'Blizzard',
//         icon: 230,
//   },
// {
//   code: 1135,
//     day: 'Fog',
//       night: 'Fog',
//         icon: 248,
//   },
// {
//   code: 1147,
//     day: 'Freezing fog',
//       night: 'Freezing fog',
//         icon: 260,
//   },
// {
//   code: 1150,
//     day: 'Patchy light drizzle',
//       night: 'Patchy light drizzle',
//         icon: 263,
//   },
// {
//   code: 1153,
//     day: 'Light drizzle',
//       night: 'Light drizzle',
//         icon: 266,
//   },
// {
//   code: 1168,
//     day: 'Freezing drizzle',
//       night: 'Freezing drizzle',
//         icon: 281,
//   },
// {
//   code: 1171,
//     day: 'Heavy freezing drizzle',
//       night: 'Heavy freezing drizzle',
//         icon: 284,
//   },
// {
//   code: 1180,
//     day: 'Patchy light rain',
//       night: 'Patchy light rain',
//         icon: 293,
//   },
// {
//   code: 1183,
//     day: 'Light rain',
//       night: 'Light rain',
//         icon: 296,
//   },
// {
//   code: 1186,
//     day: 'Moderate rain at times',
//       night: 'Moderate rain at times',
//         icon: 299,
//   },
// {
//   code: 1189,
//     day: 'Moderate rain',
//       night: 'Moderate rain',
//         icon: 302,
//   },
// {
//   code: 1192,
//     day: 'Heavy rain at times',
//       night: 'Heavy rain at times',
//         icon: 305,
//   },
// {
//   code: 1195,
//     day: 'Heavy rain',
//       night: 'Heavy rain',
//         icon: 308,
//   },
// {
//   code: 1198,
//     day: 'Light freezing rain',
//       night: 'Light freezing rain',
//         icon: 311,
//   },
// {
//   code: 1201,
//     day: 'Moderate or heavy freezing rain',
//       night: 'Moderate or heavy freezing rain',
//         icon: 314,
//   },
// {
//   code: 1204,
//     day: 'Light sleet',
//       night: 'Light sleet',
//         icon: 317,
//   },
// {
//   code: 1207,
//     day: 'Moderate or heavy sleet',
//       night: 'Moderate or heavy sleet',
//         icon: 320,
//   },
// {
//   code: 1210,
//     day: 'Patchy light snow',
//       night: 'Patchy light snow',
//         icon: 323,
//   },
// {
//   code: 1213,
//     day: 'Light snow',
//       night: 'Light snow',
//         icon: 326,
//   },
// {
//   code: 1216,
//     day: 'Patchy moderate snow',
//       night: 'Patchy moderate snow',
//         icon: 329,
//   },
// {
//   code: 1219,
//     day: 'Moderate snow',
//       night: 'Moderate snow',
//         icon: 332,
//   },
// {
//   code: 1222,
//     day: 'Patchy heavy snow',
//       night: 'Patchy heavy snow',
//         icon: 335,
//   },
// {
//   code: 1225,
//     day: 'Heavy snow',
//       night: 'Heavy snow',
//         icon: 338,
//   },
// {
//   code: 1237,
//     day: 'Ice pellets',
//       night: 'Ice pellets',
//         icon: 350,
//   },
// {
//   code: 1240,
//     day: 'Light rain shower',
//       night: 'Light rain shower',
//         icon: 353,
//   },
// {
//   code: 1243,
//     day: 'Moderate or heavy rain shower',
//       night: 'Moderate or heavy rain shower',
//         icon: 356,
//   },
// {
//   code: 1246,
//     day: 'Torrential rain shower',
//       night: 'Torrential rain shower',
//         icon: 359,
//   },
// {
//   code: 1249,
//     day: 'Light sleet showers',
//       night: 'Light sleet showers',
//         icon: 362,
//   },
// {
//   code: 1252,
//     day: 'Moderate or heavy sleet showers',
//       night: 'Moderate or heavy sleet showers',
//         icon: 365,
//   },
// {
//   code: 1255,
//     day: 'Light snow showers',
//       night: 'Light snow showers',
//         icon: 368,
//   },
// {
//   code: 1258,
//     day: 'Moderate or heavy snow showers',
//       night: 'Moderate or heavy snow showers',
//         icon: 371,
//   },
// {
//   code: 1261,
//     day: 'Light showers of ice pellets',
//       night: 'Light showers of ice pellets',
//         icon: 374,
//   },
// {
//   code: 1264,
//     day: 'Moderate or heavy showers of ice pellets',
//       night: 'Moderate or heavy showers of ice pellets',
//         icon: 377,
//   },
// {
//   code: 1273,
//     day: 'Patchy light rain with thunder',
//       night: 'Patchy light rain with thunder',
//         icon: 386,
//   },
// {
//   code: 1276,
//     day: 'Moderate or heavy rain with thunder',
//       night: 'Moderate or heavy rain with thunder',
//         icon: 389,
//   },
// {
//   code: 1279,
//     day: 'Patchy light snow with thunder',
//       night: 'Patchy light snow with thunder',
//         icon: 392,
//   },
// {
//   code: 1282,
//     day: 'Moderate or heavy snow with thunder',
//       night: 'Moderate or heavy snow with thunder',
//         icon: 395,
//   }
// };
